const seedJobs = [
  {
    postedBy: "Sally",
    applicants: ["Mary"],
    title: "Looking for cleaner",
    description: "Looking for cleaner for 3 times a week",
    type: "Cleaning",
    status: "open",
    price: 1500,
    location: "238857",
    start: "2022-12-01",
    end: "2023-02-01",
  },
  {
    postedBy: "Mary",
    applicants: ["Sally"],
    title: "Check in and deliver food to elderly",
    description: "Deliver lunch to my grandmother while I am at work",
    type: "Caregiving",
    status: "open",
    price: 100,
    location: "436962",
    start: "2023-01-27",
    end: "2023-02-16",
  },
  {
    postedBy: "Cheryl",
    applicants: ["Ryan", "Mary"],
    title: "Looking for plumber",
    description: "Finding someone to fix my leaking tap",
    type: "Handywork",
    status: "open",
    price: 50,
    location: "427395",
    start: "2022-11-22",
    end: "2022-11-22",
  },
  {
    postedBy: "Wendy",
    applicants: ["Emma"],
    title: "Looking for confinement nanny",
    description: "Looking for a nanny after my delivery",
    type: "Caregiving",
    status: "open",
    price: 3000,
    location: "120101",
    start: "2022-12-21",
    end: "2023-01-20",
  },
  {
    postedBy: "63653b3564406e7db583721d",
    applicants: ["Cheryl", "Benjamin"],
    title: "PT Sales Assistant wanted",
    description: "Part-time sale assistant for pop up store",
    type: "Event",
    status: "open",
    price: 300,
    location: "259717",
    start: "2022-11-25",
    end: "2022-11-27",
  },
  {
    postedBy: "Joshua",
    applicants: ["Jason", "Sally"],
    title: "Looking for painter",
    description: "Finding help to paint my room",
    type: "Handywork",
    status: "open",
    price: 500,
    location: "574409",
    start: "2022-12-05",
    end: "2022-12-09",
  },
  {
    postedBy: "Emma",
    acceptedBy: "Ryan",
    applicants: ["Sally", "Ryan"],
    title: "Cat sitter required",
    description: "Looking for cat sitter for my darlings",
    type: "Pets",
    status: "completed",
    price: 50,
    location: "617877",
    start: "2022-09-05",
    end: "2022-09-30",
  },
  {
    postedBy: "Benjamin",
    acceptedBy: "Sally",
    applicants: ["Sally"],
    title: "Looking for Car Wash Service",
    description: "Need help with weekly car wash at my terrace house",
    type: "Cleaning",
    status: "completed",
    price: 200,
    location: "478939",
    start: "2022-10-22",
    end: "2022-10-22",
  },
  {
    postedBy: "Sally",
    acceptedBy: "Nicholas",
    applicants: ["Nicholas"],
    title: "Need help to take care of pet dog",
    description: "Going on holidays and need someone to dog sit Bubbles for a week",
    type: "Pets",
    status: "completed",
    price: 150,
    location: "658923",
    start: "2022-11-21",
    end: "2022-11-30",
  },
  {
    postedBy: "Sally",
    applicants: ["Geraldine", "Wendy", "Mary"],
    title: "Tutor Needed",
    description: "Looking for a tutor who can teach English and Chinese",
    type: "Education",
    status: "open",
    price: 250,
    location: "188867",
    start: "2023-01-03",
    end: "2023-01-31",
  },
  {
    postedBy: "Geraldine",
    acceptedBy: "Joshua",
    applicants: ["Sally", "Cheryl", "Joshua"],
    title: "Waiter Wanted",
    description: "Wanted - banquet restaurant server for wedding",
    type: "Events",
    status: "completed",
    price: 80,
    location: "188867",
    start: "2022-10-22",
    end: "2022-10-22",
  },
  {
    postedBy: "Sally",
    acceptedBy: "Alex",
    applicants: ["Alex"],
    title: "Violin Tutor Wanted",
    description: "Looking for violin teacher with diploma",
    type: "Education",
    status: "completed",
    price: 300,
    location: "188867",
    start: "2022-08-07",
    end: "2022-10-24",
  },
];

module.exports = seedJobs;